### ISSUE TITLE
Version 25

### ISSUE THREAD

**Issue by MiiGFR** [eXtalionLab/nextcloud_docker#1]
Hello do you intend to migrate the project to use the version 25 of nextcloud ?

**Comment by d0niek** [comment]
Hi @MiiGFR!
Thanks for you message. I'vs just did it ;-)

I've upgraded nginx config in previous version `24` so it was small change.

**Comment by MiiGFR** [comment]
Thank you so much, thanks for the hard work. I will test it this evening.

**Comment by MiiGFR** [comment]
FYI it work but after the "migration" I was unable to log in into the nextcloud ( with all my admin / non admin accounts) 

- I tried resetting the admin password through occ  it didn't work 
- I create then a new account with occ, it didn't work netiher) 
- I tried again with my initial admin account and then it worked.

There must be a task running in the background taking several minutes ( DB update , or something) and until it is complete I was not able to log in. Now it works like a charm.

Thank you again.

**Comment by d0niek** [comment]
Every time when I make an update I run `docker-compose up -d && docker-compose logs -f`. It allows me to follow an update process and when it's done I goto https://your-cloud/settings/admin/overview to check if everything is ok with new version ;-)
